provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  signup:
    lang: golang-middleware
    handler: ./signup
    image: signup:latest
    labels:
      com.openfaas.scale.zero: false
    environment:
      gist_url: "https://gist.github.com/alexellis/d648d927c34c082bb5d965f06b818026"

  slack:
    lang: golang-middleware
    handler: ./slack
    image: slack:latest
    labels:
      com.openfaas.scale.zero: false
    environment:
      slack_url: "https://docs.openfaas.com/community"

  zoom:
    lang: golang-middleware
    handler: ./slack
    image: slack:latest
    labels:
      com.openfaas.scale.zero: false
    environment:
      slack_url: "https://zoom.us/j/4215401314"

  join-welcome:
    lang: python3-http
    handler: ./join-welcome
    image: alexellis/join-welcome:1.0
    labels:
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_debug: true
      combine_output: false
      content_type: application/json
      target_channel: "C4XCQR8TY"
      log_env: "0"
    secrets:
      - cloud-functions-secrets

